# Configurare conexiune PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_tel
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurare port server
server.port=8087

# Configur?ri Hibernate ?i JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Activare logare interog?ri SQL pentru debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logare suplimentar? pentru debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
